options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Install yq
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache yq

  # Step 2: Extract the version from src/main/resources/application.yml
  - name: 'alpine'
    id: ExtractVersion
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Extract the spring.version from the application.yml
        SPRING_VERSION=$(yq '.spring.version' src/main/resources/application.yml)
        echo "SPRING_VERSION=${SPRING_VERSION}" >> $HOME/version.env
        echo "Version extracted: ${SPRING_VERSION}"

  # Step 3: Source the version.env file to make SPRING_VERSION available in subsequent steps
  - name: 'alpine'
    id: SourceVersion
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        source $HOME/version.env
        echo "Using SPRING_VERSION: ${SPRING_VERSION}"

  # Step 4: Build the Docker image with the version tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-batis-test-$COMMIT_SHA:${SPRING_VERSION}'  # Use SPRING_VERSION directly
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/my-batis-test-$COMMIT_SHA:${SPRING_VERSION}'
