steps:
  # Step 1: Install yq
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache yq

  # Step 2: Extract the version from application.yml
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        SPRING_VERSION=$(yq '.spring.version' application.yml)
        echo "SPRING_VERSION=${SPRING_VERSION}" >> version.env

  # Step 3: Build the Docker image with the version and commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-batis-test:${_SPRING_VERSION}-$COMMIT_SHA'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/my-batis-test:${_SPRING_VERSION}-$COMMIT_SHA'
