options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SPRING_VERSION: ''  # Placeholder for SPRING_VERSION to be set during trigger or build

steps:
  # Step 1: Install yq
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache yq

  # Step 2: Extract the version from application.yml and set it as a substitution
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        SPRING_VERSION=$(yq '.spring.version' application.yml)
        echo "SPRING_VERSION=${SPRING_VERSION}" > version.env
        # Use gcloud to set the substitution value dynamically
        gcloud builds submit --substitutions=_SPRING_VERSION=${SPRING_VERSION}

  # Step 3: Build the Docker image with the version tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-batis-test-$COMMIT_SHA:${_SPRING_VERSION}'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/my-batis-test-$COMMIT_SHA:${_SPRING_VERSION}'
